### ISSUE TITLE
sobra????????????????

### ISSUE THREAD

**Issue by lmagarin** [alesjora/DWEC#3]
https://github.com/alesjora/DWEC/blob/eb42a347c4617c2260096f61d10201767b4c4f5a/Tema%206/Buscaminas%20con%20jQuery/js/main.js#L375

**Comment by alesjora** [comment]
Sí, sin la línea sigue funcionando correctamente. Con respecto a la duda que teníamos con off() y eliminar eventos sin pasar la función, he estado probando y funciona. No hace falta pasar el nombre de la función para eliminar algún evento.
